using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Windows;

namespace LauncherTF2.Core;

/// <summary>
/// Attached property that tags an element with a stable anchor name and
/// registers it in a per-host registry. The settings sidebar uses this to
/// scroll to a category by ID without naming each section in XAML — items
/// generated by a DataTemplate (where x:Name isn't usable from outside) are
/// addressable too.
///
/// Each host (typically a ScrollViewer or its content panel) owns its own
/// registry, indexed by anchor name → element. The registry is keyed off
/// the nearest tagged element's logical scope so multiple settings views
/// can coexist without trampling each other.
/// </summary>
public static class ScrollAnchor
{
    private static readonly ConditionalWeakTable<DependencyObject, ConcurrentDictionary<string, FrameworkElement>>
        Registries = new();

    public static readonly DependencyProperty NameProperty =
        DependencyProperty.RegisterAttached(
            "Name", typeof(string), typeof(ScrollAnchor),
            new PropertyMetadata(null, OnNameChanged));

    public static string? GetName(DependencyObject d) => (string?)d.GetValue(NameProperty);
    public static void SetName(DependencyObject d, string? v) => d.SetValue(NameProperty, v);

    public static readonly DependencyProperty HostProperty =
        DependencyProperty.RegisterAttached(
            "Host", typeof(DependencyObject), typeof(ScrollAnchor),
            new PropertyMetadata(null));

    /// <summary>The element under which this anchor's registry lives (typically the ScrollViewer).</summary>
    public static DependencyObject? GetHost(DependencyObject d) => (DependencyObject?)d.GetValue(HostProperty);
    public static void SetHost(DependencyObject d, DependencyObject? v) => d.SetValue(HostProperty, v);

    private static void OnNameChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is not FrameworkElement fe) return;
        var name = (string?)e.NewValue;
        if (string.IsNullOrEmpty(name)) return;

        // Defer host resolution until the element is in the visual tree so we
        // can walk up to its ScrollViewer host. The Loaded event is reliable
        // for both XAML-declared anchors and DataTemplate-generated ones.
        if (fe.IsLoaded) Register(fe, name);
        else fe.Loaded += (_, _) => Register(fe, name);
        fe.Unloaded += (_, _) => Unregister(fe, name);
    }

    private static void Register(FrameworkElement fe, string name)
    {
        var host = GetHost(fe) ?? FindHost(fe);
        if (host == null) return;
        var reg = Registries.GetValue(host, _ => new ConcurrentDictionary<string, FrameworkElement>(StringComparer.OrdinalIgnoreCase));
        reg[name] = fe;
        try
        {
            LauncherTF2.Core.Logger.LogDebug($"[ScrollAnchor] Registered anchor '{name}' under host {host.GetType().Name}");
        }
        catch { }
    }

    private static void Unregister(FrameworkElement fe, string name)
    {
        var host = GetHost(fe) ?? FindHost(fe);
        if (host == null) return;
        if (Registries.TryGetValue(host, out var reg))
            reg.TryRemove(name, out _);
    }

    private static DependencyObject? FindHost(DependencyObject start)
    {
        // Walk up looking for an explicit Host marker; fall back to the first
        // ScrollViewer ancestor. Anchors set up before the visual tree is
        // ready will retry on Loaded so this can return null safely.
        var p = System.Windows.Media.VisualTreeHelper.GetParent(start);
        while (p != null)
        {
            if (p is System.Windows.Controls.ScrollViewer sv) return sv;
            p = System.Windows.Media.VisualTreeHelper.GetParent(p);
        }
        return null;
    }

    /// <summary>Resolve an anchor name registered under <paramref name="host"/>, or null when missing.</summary>
    public static FrameworkElement? Find(DependencyObject host, string name)
    {
        if (Registries.TryGetValue(host, out var reg) && reg.TryGetValue(name, out var fe))
            return fe;
        try
        {
            LauncherTF2.Core.Logger.LogDebug($"[ScrollAnchor] Could not find anchor '{name}' under host {host.GetType().Name}");
        }
        catch { }
        return null;
    }

    /// <summary>All currently-registered anchor pairs under <paramref name="host"/>.</summary>
    public static IEnumerable<KeyValuePair<string, FrameworkElement>> All(DependencyObject host)
    {
        if (Registries.TryGetValue(host, out var reg)) return reg.ToArray();
        return Array.Empty<KeyValuePair<string, FrameworkElement>>();
    }
}
