using LauncherTF2.Models;
using System.IO;
using System.Text;

namespace LauncherTF2.Services;

public class AutoexecWriter
{
    public static void WriteToAutoexec(SettingsModel settings, string tfPath)
    {
        string cfgPath = Path.Combine(tfPath, "cfg", "autoexec.cfg");

        // Ensure directory exists
        string? cfgDir = Path.GetDirectoryName(cfgPath);
        if (cfgDir != null && !Directory.Exists(cfgDir))
        {
            Directory.CreateDirectory(cfgDir);
        }

        StringBuilder sb = new();

        sb.AppendLine("// Auto-generated by Eternal Launcher");
        sb.AppendLine("// DO NOT EDIT THIS SECTION MANUALLY, IT WILL BE OVERWRITTEN");
        sb.AppendLine("");

        // Launch Options / System
        sb.AppendLine("// System");
        if (settings.SkipIntro) sb.AppendLine("-novid"); // Note: Launch args cannot be in autoexec, this is for reference or if we write a launch script later.
                                                         // Actually, we shouldn't write launch args to autoexec. They go in steam.
                                                         // We only write console variable commands here.

        // Graphics
        sb.AppendLine("// Graphics");
        sb.AppendLine($"mat_vsync {(settings.VSync ? "1" : "0")}");
        sb.AppendLine($"mat_antialias {settings.AntiAliasing}");
        sb.AppendLine($"mat_forceaniso {settings.AnisotropicFiltering}");
        sb.AppendLine($"mat_disable_bloom {(settings.Bloom ? "0" : "1")}");
        sb.AppendLine($"motion_blur_strength {settings.MotionBlurStrength}");
        sb.AppendLine($"r_lod {settings.ModelLod}");
        sb.AppendLine($"cl_ragdoll_physics_enable {(settings.Ragdolls ? "1" : "0")}");
        sb.AppendLine($"violence_agibs {(settings.AlienGibs ? "1" : "0")}");
        sb.AppendLine($"violence_hgibs {(settings.HumanGibs ? "1" : "0")}");
        sb.AppendLine($"cl_detaildist {settings.DetailDistance}");

        // Gameplay
        sb.AppendLine("");
        sb.AppendLine("// Gameplay");
        sb.AppendLine($"fov_desired {settings.Fov}");
        sb.AppendLine($"viewmodel_fov {settings.ViewmodelFov}");
        sb.AppendLine($"r_drawviewmodel {(settings.DrawViewmodel ? "1" : "0")}");
        sb.AppendLine($"m_rawinput {(settings.RawInput ? "1" : "0")}");
        sb.AppendLine($"sensitivity {settings.MouseSensitivity}");
        sb.AppendLine($"cl_autoreload {(settings.AutoReload ? "1" : "0")}");
        sb.AppendLine($"tf_dingalingaling {(settings.HitSound ? "1" : "0")}");
        sb.AppendLine($"hud_combattext {(settings.DamageNumbers ? "1" : "0")}");
        sb.AppendLine($"tf_killstreak_sheen_brightness {settings.KillstreakGlow}");

        // Interface
        sb.AppendLine("");
        sb.AppendLine("// Interface");
        sb.AppendLine($"net_graph {(settings.NetGraph ? "1" : "0")}");
        sb.AppendLine($"hud_saytext_time {settings.ChatMessageTime}");
        sb.AppendLine($"cl_drawhud {(settings.DrawHud ? "1" : "0")}");

        // Network
        sb.AppendLine("");
        sb.AppendLine("// Network & Pro");
        sb.AppendLine($"cl_interp {settings.Interp}");
        sb.AppendLine($"cl_interpolate {(settings.Interpolate ? "1" : "0")}");
        sb.AppendLine($"rate {settings.Rate}");
        sb.AppendLine($"cl_cmdrate {settings.CmdRate}");
        sb.AppendLine($"cl_updaterate {settings.UpdateRate}");
        sb.AppendLine($"mat_queue_mode {settings.QueueMode}");
        sb.AppendLine($"r_eyes {(settings.DisableEyes ? "0" : "1")}");
        sb.AppendLine($"r_flex {(settings.DisableFlex ? "0" : "1")}");

        // Advanced (Hidden)
        sb.AppendLine("");
        sb.AppendLine("// Advanced");
        sb.AppendLine($"cl_showbackpackrarities {(settings.ShowBackpackRarities ? "1" : "0")}");
        sb.AppendLine($"cl_notifications_show_ingame {(settings.ShowIngameNotifications ? "1" : "0")}");
        sb.AppendLine($"cl_showpluginmessages {(settings.ShowPluginMessages ? "1" : "0")}");
        sb.AppendLine($"cl_showhelp {(settings.ShowHelp ? "1" : "0")}");
        sb.AppendLine($"tf_scoreboard_ping_as_text {(settings.ScoreboardPingText ? "1" : "0")}");
        sb.AppendLine($"cl_spec_mode {settings.SpectatorMode}");
        sb.AppendLine($"cl_new_impact_effects {(settings.NewImpactEffects ? "1" : "0")}");
        sb.AppendLine($"r_drawtracers_firstperson {(settings.DrawTracersFirstPerson ? "1" : "0")}");
        sb.AppendLine($"tf_colorblindassist {(settings.ColorblindAssist ? "1" : "0")}");

        // Binds
        sb.AppendLine("");
        sb.AppendLine("// Binds");
        foreach (var bind in settings.Binds)
        {
            if (!string.IsNullOrWhiteSpace(bind.Key) && !string.IsNullOrWhiteSpace(bind.Command))
            {
                sb.AppendLine($"bind \"{bind.Key}\" \"{bind.Command}\"");
            }
        }

        try
        {
            File.WriteAllText(cfgPath, sb.ToString());
        }
        catch (Exception)
        {
            // Handle error logging
        }
    }
}
